# Generated by Django 5.2.12 on 2026-04-15 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_emergency_phone_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Conditions Générales d'Utilisation", max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Condition d'utilisation",
                'verbose_name_plural': "Conditions d'utilisation",
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='CGU acceptées'),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20, verbose_name='Version CGU acceptée'),
        ),
        migrations.CreateModel(
            name='UserTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.termsofservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceptation des conditions',
                'verbose_name_plural': 'Acceptations des conditions',
                'unique_together': {('user', 'terms')},
            },
        ),
    ]
