# Generated by Django 6.0.3 on 2026-04-02 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('en_creation', 'En création'), ('active', 'Active'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_creation', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('bi_weekly', 'Bi-hebdomadaire'), ('monthly', 'Mensuel')], default='monthly', max_length=20)),
                ('amount_per_member', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_members', models.PositiveIntegerField(default=20)),
                ('min_members', models.PositiveIntegerField(default=3)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tontines/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tontines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tontine',
                'verbose_name_plural': 'Tontines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annule', 'Annulée')], default='en_cours', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_per_member', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['-number'],
                'unique_together': {('tontine', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TontineMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tresorier', 'Trésorier'), ('membre', 'Membre')], default='membre', max_length=20)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('quitte', 'Quitté')], default='en_attente', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tontines.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de Tontine',
                'verbose_name_plural': 'Membres de Tontine',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('tontine', 'user')},
            },
        ),
    ]
