# Generated by Django 5.2.12 on 2026-04-03 23:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('successful_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('failed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('orange_transactions', models.IntegerField(default=0)),
                ('orange_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wave_transactions', models.IntegerField(default=0)),
                ('wave_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('stripe_transactions', models.IntegerField(default=0)),
                ('stripe_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cache Dashboard',
                'verbose_name_plural': 'Caches Dashboard',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, help_text='Identifiant unique de la transaction', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('orange_money', 'Orange Money'), ('wave', 'Wave'), ('stripe', 'Stripe (Cartes)')], help_text='Provider de paiement utilisé', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en XOF', max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('success', 'Succès'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé'), ('retry_scheduled', 'Retry planifié'), ('max_retries_exceeded', 'Max retries dépassé')], default='pending', max_length=30)),
                ('retry_count', models.IntegerField(default=0, help_text='Nombre de tentatives de retry')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Date du prochain retry', null=True)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Données de la requête API')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Données de la réponse API')),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si échec")),
                ('callback_data', models.JSONField(blank=True, default=dict, help_text='Données reçues par webhook')),
                ('payment_url', models.URLField(blank=True, help_text='URL de redirection vers le provider')),
                ('external_transaction_id', models.CharField(blank=True, help_text='ID de transaction chez le provider', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='contributions.contribution')),
                ('tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='tontines.tontine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de Transaction',
                'verbose_name_plural': 'Journaux de Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('provider', models.CharField(choices=[('africas_talking', "Africa's Talking"), ('orange', 'Orange SMS')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('delivered', 'Livré'), ('failed', 'Échoué'), ('retry', 'En retry')], default='pending', max_length=20)),
                ('notification_type', models.CharField(blank=True, default='general', max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='payments.transactionlog')),
            ],
            options={
                'verbose_name': 'Log Notification SMS',
                'verbose_name_plural': 'Logs Notifications SMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_id'], name='payments_tr_transac_1fe1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['provider', 'status'], name='payments_tr_provide_cd7360_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='payments_tr_created_714f6a_idx'),
        ),
    ]
