# Generated by Django 6.0.3 on 2026-04-02 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('contributions', 'Rapport des cotisations'), ('draws', 'Rapport des tirages'), ('members', 'Rapport des membres'), ('financial', 'Rapport financier'), ('cycle', 'Rapport de cycle'), ('general', 'Rapport général')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='html', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'En cours de génération'), ('ready', 'Prêt'), ('failed', 'Échoué')], default='generating', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_contributions_count', models.PositiveIntegerField(default=0)),
                ('validated_contributions', models.PositiveIntegerField(default=0)),
                ('rejected_contributions', models.PositiveIntegerField(default=0)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payouts_count', models.PositiveIntegerField(default=0)),
                ('total_draws', models.PositiveIntegerField(default=0)),
                ('total_winners', models.PositiveIntegerField(default=0)),
                ('total_winnings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('left_members', models.PositiveIntegerField(default=0)),
                ('participation_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'ordering': ['-year', '-month'],
                'unique_together': {('tontine', 'year', 'month')},
            },
        ),
    ]
