# Generated by Django 6.0.3 on 2026-04-02 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annule', 'Annulée')], default='planifie', max_length=20)),
                ('selection_method', models.CharField(choices=[('aleatoire', 'Aléatoire'), ('ordre_arrivee', "Ordre d'arrivée"), ('cycle', 'Par cycle'), ('consensus', 'Consensus des membres')], default='aleatoire', max_length=30)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('total_pot', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('winner_count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_draws', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='tontines.cycle')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='tontines.tontine')),
            ],
            options={
                'verbose_name': 'Tirage',
                'verbose_name_plural': 'Tirages',
                'ordering': ['-draw_date'],
            },
        ),
        migrations.CreateModel(
            name='DrawHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='draws.draw')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de tirage',
                'verbose_name_plural': 'Historiques de tirages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('exclusion_reason', models.CharField(blank=True, max_length=200)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='draws.draw')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant au tirage',
                'verbose_name_plural': 'Participants aux tirages',
                'unique_together': {('draw', 'user')},
            },
        ),
        migrations.AddField(
            model_name='draw',
            name='eligible_participants',
            field=models.ManyToManyField(related_name='eligible_draws', through='draws.DrawParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('transfert_en_cours', 'Transfert en cours'), ('transfert_reussi', 'Transfert réussi'), ('transfert_echec', 'Échec du transfert'), ('recu', 'Reçu par le gagnant')], default='en_attente', max_length=30)),
                ('payout_reference', models.CharField(blank=True, max_length=100)),
                ('notification_sent', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.draw')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gagnant',
                'verbose_name_plural': 'Gagnants',
                'ordering': ['position'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='draw',
            unique_together={('cycle', 'number')},
        ),
    ]
